package report

import (
	"bytes"
	"fmt"
	"sort"
	"text/template"
	"time"

	"github.com/your-org/kost/internal/engine"
)

const markdownTemplate = `# kost Report

**Generated**: {{.GeneratedAt.Format "2006-01-02 15:04:05"}}

## Analysis Parameters

- **Namespace**: {{.Namespace}}
- **Analysis Window**: {{.Window}}
- **Percentile**: {{.Percentile}}
- **Safety Factor**: {{printf "%.1f" .SafetyFactor}}

---

## Summary

- **Total Containers Analyzed**: {{.TotalContainers}}
- **Overprovisioned Containers**: {{.OverprovisionedCount}}
- **Underprovisioned Containers**: {{.UnderprovisionedCount}}
- **Appropriate Containers**: {{.AppropriateCount}}
- **Total Potential Savings**: {{printf "%.1f%%" .TotalSavingsPercent}}

---

## Top Findings

{{range .TopFindings}}
### {{.Rank}}. {{.Deployment}} / {{.Container}}

**Status**: {{.Status}}

**CPU**:
- Current Request: {{if .CurrentCPU}}{{.CurrentCPU}}m{{else}}not set{{end}}
- Recommended Request: {{.RecommendedCPU}}m
- P95 Usage: {{printf "%.0f" .CPUP95}}m
- Judgement: **{{.CPUJudgement}}**
{{if gt .CPUSaving 0.0}}- Potential Saving: {{printf "%.1f%%" .CPUSaving}}
{{else if lt .CPUSaving 0.0}}- Increase Needed: {{printf "%.1f%%" .CPUIncrease}}
{{end}}

**Memory**:
- Current Request: {{if .CurrentMem}}{{.CurrentMem}}Mi{{else}}not set{{end}}
- Recommended Request: {{.RecommendedMem}}Mi
- P95 Usage: {{printf "%.0f" .MemP95}}Mi
- Judgement: **{{.MemJudgement}}**
{{if gt .MemSaving 0.0}}- Potential Saving: {{printf "%.1f%%" .MemSaving}}
{{else if lt .MemSaving 0.0}}- Increase Needed: {{printf "%.1f%%" .MemIncrease}}
{{end}}

**Rationale**:
- Safety Factor Applied: {{printf "%.1f" .SafetyFactor}}
- Minimum CPU Threshold: {{.MinCPUMilli}}m
- Minimum Memory Threshold: {{.MinMemMi}}Mi

{{if .Narrative}}**AI Analysis**:
{{.Narrative}}
{{end}}

---
{{end}}

## Suggested Patches

Apply the recommended changes using the generated patch files:

{{range .PatchFiles}}
- ` + "`{{.}}`" + `
{{end}}

{{if .PatchFiles}}**Apply patches**:
` + "```bash" + `
# Review patches first
cat {{index .PatchFiles 0}}

# Dry-run to verify
kubectl apply -f {{.PatchDir}} --dry-run=client

# Apply when ready
kubectl apply -f {{.PatchDir}}
` + "```" + `
{{end}}

---

## Methodology

**CPU Recommendation**:
- Formula: ` + "`max(P95(rate(container_cpu_usage_seconds_total[5m])) × SafetyFactor, MinCPU)`" + `
- Percentile: P{{printf "%.0f" .CPUPercentile}}
- Safety Factor: {{printf "%.1f" .SafetyFactor}}

**Memory Recommendation**:
- Formula: ` + "`max(P95(container_memory_working_set_bytes) × SafetyFactor, MinMemory)`" + `
- Percentile: P{{printf "%.0f" .MemPercentile}}
- Safety Factor: {{printf "%.1f" .SafetyFactor}}

**Judgement Criteria**:
- **Overprovisioned**: Current > P95 × 2.0
- **Underprovisioned**: Current < P95 × 1.1
- **Appropriate**: Within optimal range

---

## Next Steps

1. **Review** the recommendations above
2. **Test** patches in a non-production environment first
3. **Monitor** application performance after applying changes
4. **Adjust** if needed based on actual workload behavior

---

*Generated by [kost](https://github.com/your-org/kost) - Kubernetes Optimization & Sizing Tool*
`

// MarkdownFinding represents a single finding for the markdown template
type MarkdownFinding struct {
	Rank           int
	Deployment     string
	Container      string
	Status         string
	CurrentCPU     *int
	RecommendedCPU int
	CPUP95         float64
	CPUJudgement   string
	CPUSaving      float64
	CPUIncrease    float64
	CurrentMem     *int
	RecommendedMem int
	MemP95         float64
	MemJudgement   string
	MemSaving      float64
	MemIncrease    float64
	SafetyFactor   float64
	MinCPUMilli    int
	MinMemMi       int
	Narrative      string
}

// MarkdownData represents data for the markdown template
type MarkdownData struct {
	GeneratedAt            time.Time
	Namespace              string
	Window                 string
	Percentile             string
	SafetyFactor           float64
	CPUPercentile          float64
	MemPercentile          float64
	TotalContainers        int
	OverprovisionedCount   int
	UnderprovisionedCount  int
	AppropriateCount       int
	TotalSavingsPercent    float64
	TopFindings            []MarkdownFinding
	PatchFiles             []string
	PatchDir               string
}

// GenerateMarkdown generates a markdown report from recommendations
func GenerateMarkdown(report *Report) (string, error) {
	// Sort recommendations by total saving ratio (descending)
	sortedRecs := make([]engine.ResourceRecommendation, len(report.ResourceRecommendations))
	copy(sortedRecs, report.ResourceRecommendations)

	sort.Slice(sortedRecs, func(i, j int) bool {
		savingI := sortedRecs[i].CPUSavingRatio + sortedRecs[i].MemSavingRatio
		savingJ := sortedRecs[j].CPUSavingRatio + sortedRecs[j].MemSavingRatio
		return savingI > savingJ
	})

	// Calculate summary statistics
	overprovisioned := 0
	underprovisioned := 0
	appropriate := 0
	totalSaving := 0.0

	for _, rec := range report.ResourceRecommendations {
		if rec.CPUJudgement == "overprovisioned" || rec.MemJudgement == "overprovisioned" {
			overprovisioned++
		} else if rec.CPUJudgement == "underprovisioned" || rec.MemJudgement == "underprovisioned" {
			underprovisioned++
		} else {
			appropriate++
		}

		// Average saving across CPU and Memory
		avgSaving := (rec.CPUSavingRatio + rec.MemSavingRatio) / 2.0
		if avgSaving > 0 {
			totalSaving += avgSaving
		}
	}

	// Calculate average saving percentage
	totalSavingsPercent := 0.0
	if len(report.ResourceRecommendations) > 0 {
		totalSavingsPercent = (totalSaving / float64(len(report.ResourceRecommendations))) * 100
	}

	// Build top findings
	topFindings := []MarkdownFinding{}
	for i, rec := range sortedRecs {
		status := "📊 Needs Attention"
		if rec.CPUJudgement == "overprovisioned" || rec.MemJudgement == "overprovisioned" {
			status = "📉 Overprovisioned"
		} else if rec.CPUJudgement == "underprovisioned" || rec.MemJudgement == "underprovisioned" {
			status = "📈 Underprovisioned"
		} else {
			status = "✅ Appropriate"
		}

		finding := MarkdownFinding{
			Rank:           i + 1,
			Deployment:     rec.Deployment,
			Container:      rec.Container,
			Status:         status,
			CurrentCPU:     rec.CurrentCPURequestMilli,
			RecommendedCPU: rec.RecommendedCPURequestMilli,
			CPUP95:         rec.Rationale.CPUP95,
			CPUJudgement:   rec.CPUJudgement,
			CPUSaving:      rec.CPUSavingRatio * 100,
			CPUIncrease:    -rec.CPUSavingRatio * 100,
			CurrentMem:     rec.CurrentMemRequestMi,
			RecommendedMem: rec.RecommendedMemRequestMi,
			MemP95:         rec.Rationale.MemP95,
			MemJudgement:   rec.MemJudgement,
			MemSaving:      rec.MemSavingRatio * 100,
			MemIncrease:    -rec.MemSavingRatio * 100,
			SafetyFactor:   rec.Rationale.SafetyFactor,
			MinCPUMilli:    rec.Rationale.MinCPUMilli,
			MinMemMi:       rec.Rationale.MinMemMi,
			Narrative:      "", // Will be populated by LLM if enabled
		}

		topFindings = append(topFindings, finding)
	}

	// Build patch files list
	patchFiles := []string{}
	deploymentSet := make(map[string]bool)
	for _, rec := range report.ResourceRecommendations {
		if !deploymentSet[rec.Deployment] {
			patchFiles = append(patchFiles, fmt.Sprintf("patches/%s/%s.yaml", report.Namespace, rec.Deployment))
			deploymentSet[rec.Deployment] = true
		}
	}

	// Prepare template data
	data := MarkdownData{
		GeneratedAt:            report.GeneratedAt,
		Namespace:              report.Namespace,
		Window:                 report.Window,
		Percentile:             report.Percentile,
		SafetyFactor:           report.SafetyFactor,
		CPUPercentile:          95.0, // TODO: Get from config
		MemPercentile:          95.0, // TODO: Get from config
		TotalContainers:        len(report.ResourceRecommendations),
		OverprovisionedCount:   overprovisioned,
		UnderprovisionedCount:  underprovisioned,
		AppropriateCount:       appropriate,
		TotalSavingsPercent:    totalSavingsPercent,
		TopFindings:            topFindings,
		PatchFiles:             patchFiles,
		PatchDir:               fmt.Sprintf("patches/%s/", report.Namespace),
	}

	// Parse and execute template
	tmpl, err := template.New("markdown").Parse(markdownTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse markdown template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute markdown template: %w", err)
	}

	return buf.String(), nil
}
